name: Slither 
on:
  workflow_dispatch:
  schedule: ## schedule the job to run at 12 am daily
     - cron: '0 0 * * *'

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crytic/slither-action@v0.3.1
#    with:
#      args: --severity-threshold=high